function [Data,StopInfo] = read_RCA_RCAPHYTREACTION(FileToRead,GridInfo,iStep)
% 
% 
% 

NX = GridInfo.nx;
NY = GridInfo.ny;
NZ = GridInfo.nz-1;
% reading format
restartName = {...
    'useless01' 'TIME' 'useless02'...
    'useless11' 'GPP' 'useless12'...
    'useless21' 'RESP' 'useless22'...
    'useless31' 'GRAZ' 'useless32' ... 
    'useless41' 'DEPS' 'useless42' ...
    };
restartFormat = {...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
        };
restartDim = {...
    [1 1]   [1 1]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...   
      };
restartMap = [restartFormat' restartDim' restartName'];
%
Data.GPP=nan(NX,NY,NZ);
Data.RESP=nan(NX,NY,NZ);
Data.GRAZ=nan(NX,NY,NZ);
Data.DEPS=nan(NX,NY,NZ);
% for iStep = iniStep:endStep
try
    m = memmapfile(...
        FileToRead ,...
        'Format',restartMap,...
        'Writable', true, ...
        'Repeat',1, ...
        'offset',(iStep-1)*4*(3+4*(NX*NY*NZ+2))...
        );
    mdata = m.data;
catch ME
    StopInfo.StopStep = iStep-1;
    StopInfo.EndOfFile = 1;
    StopInfo.ME = ME;
    return;
end
StopInfo.StopStep = iStep;
StopInfo.EndOfFile = 0;

%
Data.time=double(mdata.TIME)
Data.GPP=double(mdata.GPP);
Data.RESP=double(mdata.RESP);
Data.GRAZ=double(mdata.GRAZ);
Data.DEPS=double(mdata.DEPS);
return
end