function [Data,StopInfo] = read_ecom_ts_trans(FileToRead,GridInfo,iStep)
% 
% 
% 
NX = GridInfo.nx;
NY = GridInfo.ny;
NZ = GridInfo.nz;
% reading format
restartName = {...
    'useless11' 'time' 'useless12'...
    'useless21' 'PAR' 'useless22'...
    'useless31' 'HADV' 'useless32'...
    'useless41' 'VADV' 'useless42' ... 
    'useless51' 'HDIF' 'useless52' ...
    'useless61' 'VDIF' 'useless62' ...
    'useless71' 'VDIF2' 'useless72' ...
    };
restartFormat = {...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
        };
restartDim = {...
    [1 1]      [1 1]    [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...  
    [1 1]   [NX NY NZ]  [1 1] ... 
      };
restartMap = [restartFormat' restartDim' restartName'];
%
Data.PAR=nan(NX,NY,NZ);
Data.HADV=nan(NX,NY,NZ);
Data.VADV=nan(NX,NY,NZ);
Data.HDIF=nan(NX,NY,NZ);
Data.VDIF=nan(NX,NY,NZ);
Data.VDIF2=nan(NX,NY,NZ);
%
try
    m = memmapfile(...
        FileToRead ,...
        'Format',restartMap,...
        'Writable', true, ...
        'Repeat',1, ...
        'offset',(iStep-1)*4*(3+6*(NX*NY*NZ+2))...
        );
    mdata = m.data;
catch ME
    StopInfo.StopStep = iStep-1;
    StopInfo.EndOfFile = 1;
    StopInfo.ME = ME;
    return;
end
StopInfo.StopStep = iStep;
StopInfo.EndOfFile = 0;
%
Data.time=double(mdata.time);
Data.PAR=double(mdata.PAR);
Data.HADV=double(mdata.HADV);
Data.VADV=double(mdata.VADV);
Data.HDIF=double(mdata.HDIF);
Data.VDIF=double(mdata.VDIF);
Data.VDIF2=double(mdata.VDIF2);
return
end