[figure_handle,count,speeds,directions,Table] = ...
            WindRose_ORI(OBSangleVec,OBSspeedVec,...
            'titlestring','a',...
            'speedround',[0:10:50],...
            'maxfrequency',20,...
            'legendvariable','v',...
            'lablegend','velocity(cm/s)',...
            'anglenorth',0,...
            'angleeast',90);