function [Data,StopInfo] = read_RCA_RCADOREACTION(FileToRead,GridInfo,iStep)
% 
% 
% 

NX = GridInfo.nx;
NY = GridInfo.ny;
NZ = GridInfo.nz-1;
% reading format
restartName = {...
    'useless11' 'rea' 'useless12'...
    'useless21' 'phot' 'useless22'...
    'useless31' 'resp' 'useless32' ... 
    'useless41' 'nitri' 'useless42' ...
    'useless51' 'oxdi' 'useless52' ...
    'useless61' 'unknown' 'useless62' ...
    'useless71' 'netDO' 'useless72' ...
    };
restartFormat = {...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
        };
restartDim = {...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...    
      };
restartMap = [restartFormat' restartDim' restartName'];
%
Data.rea=nan(NX,NY,NZ);
Data.phot=nan(NX,NY,NZ);
Data.resp=nan(NX,NY,NZ);
Data.nitri=nan(NX,NY,NZ);
Data.oxdi=nan(NX,NY,NZ);
Data.unknown=nan(NX,NY,NZ);
Data.netDO=nan(NX,NY,NZ);

% for iStep = iniStep:endStep
try
    m = memmapfile(...
        FileToRead ,...
        'Format',restartMap,...
        'Writable', true, ...
        'Repeat',1, ...
        'offset',(iStep-1)*4*7*(NX*NY*NZ+2)...
        );
    mdata = m.data;
catch ME
    StopInfo.StopStep = iStep-1;
    StopInfo.EndOfFile = 1;
    StopInfo.ME = ME;
    return;
end
StopInfo.StopStep = iStep;
StopInfo.EndOfFile = 0;

%
Data.rea=double(mdata.rea);
Data.phot=double(mdata.phot);
Data.resp=double(mdata.resp);
Data.nitri=double(mdata.nitri);
Data.oxdi=double(mdata.oxdi);
Data.unknown=double(mdata.unknown);
Data.netDO=double(mdata.netDO);
return
end