function [Data,StopInfo] = read_RCA_RCAF11(FileToRead,GridInfo,iStep)
% 
% 
% 
NX = GridInfo.nx;
NY = GridInfo.ny;
NZ = GridInfo.nz-1;
% reading format
restartName = {...
    'useless11' 'Salinity' 'useless12'...
    'useless21' 'Phyt1' 'useless22'...
    'useless31' 'Phyt2' 'useless32' ... 
    'useless41' 'Phyt3' 'useless42' ...
    'useless51' 'TPOP' 'useless52' ...
    'useless61' 'TDOP' 'useless62' ...
    'useless71' 'DPO4' 'useless72' ...
    'useless81' 'TPON' 'useless82' ...
    'useless91' 'TDON' 'useless92' ...
    'useless101' 'DNH4' 'useless102' ...
    'useless111' 'NO23' 'useless112' ...
    'useless121' 'TPSi' 'useless122' ...
    'useless131' 'DSi' 'useless132' ...
    'useless141' 'TPOC' 'useless142' ...
    'useless151' 'TDOC' 'useless152' ...
    'useless161' 'O2EQ' 'useless162' ...
    'useless171' 'DOAVE' 'useless172'...
    'useless181' 'DOMIN' 'useless182' ...
    'useless191' 'DOMAX' 'useless192' ...
    'useless201' 'ECOMSal' 'useless202' ...
    'useless211' 'Chlave' 'useless212' ...
    'useless221' 'Chlmin' 'useless222' ...
    'useless231' 'Chlmax' 'useless232' ...
    'useless241' 'Gross_PP' 'useless242' ...
    'useless251' 'NetPP' 'useless252' ...
    'useless261' 'TResp' 'useless262' ...
    'useless271' 'ECOMTemp' 'useless272' ...
    'useless281' 'SKE'  'useless282'  ...
    };
restartFormat = {...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
    'uint32'  'single' 'uint32' ...
        };
restartDim = {...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...
    [1 1]   [NX NY NZ]  [1 1] ...    
      };
restartMap = [restartFormat' restartDim' restartName'];
%
Data.salt=nan(NX,NY,NZ);
Data.phyt1=nan(NX,NY,NZ);
Data.phyt2=nan(NX,NY,NZ);
Data.phyt3=nan(NX,NY,NZ);
Data.tpop=nan(NX,NY,NZ);
Data.tdop=nan(NX,NY,NZ);
Data.dpo4=nan(NX,NY,NZ);
Data.tpon=nan(NX,NY,NZ);
Data.tdon=nan(NX,NY,NZ);
Data.dnh4=nan(NX,NY,NZ);
Data.no23=nan(NX,NY,NZ);
Data.tpsi=nan(NX,NY,NZ);
Data.dsi=nan(NX,NY,NZ);
Data.tpoc=nan(NX,NY,NZ);
Data.tdoc=nan(NX,NY,NZ);
Data.o2eq=nan(NX,NY,NZ);
Data.doave=nan(NX,NY,NZ);
Data.domin=nan(NX,NY,NZ);
Data.domax=nan(NX,NY,NZ);
Data.ecomsal=nan(NX,NY,NZ);
Data.chlave=nan(NX,NY,NZ);
Data.chlmin=nan(NX,NY,NZ);
Data.chlmax=nan(NX,NY,NZ);
Data.gross_pp=nan(NX,NY,NZ);
Data.netpp=nan(NX,NY,NZ);
Data.tresp=nan(NX,NY,NZ);
Data.ecomtemp=nan(NX,NY,NZ);
Data.ske=nan(NX,NY,NZ);

% for iStep = iniStep:endStep
try
    m = memmapfile(...
        FileToRead ,...
        'Format',restartMap,...
        'Writable', true, ...
        'Repeat',1, ...
        'offset',(iStep-1)*4*28*(NX*NY*NZ+2)...
        );
    mdata = m.data;
catch ME
    StopInfo.StopStep = iStep-1;
    StopInfo.EndOfFile = 1;
    StopInfo.ME = ME;
    return;
end
StopInfo.StopStep = iStep;
StopInfo.EndOfFile = 0;

%
Data.salt=double(mdata.Salinity);
Data.phyt1=double(mdata.Phyt1);
Data.phyt2=double(mdata.Phyt2);
Data.phyt3=double(mdata.Phyt3);
Data.tpop=double(mdata.TPOP);
Data.tdop=double(mdata.TDOP);
Data.dpo4=double(mdata.DPO4);
Data.tpon=double(mdata.TPON);
Data.tdon=double(mdata.TDON);
Data.dnh4=double(mdata.DNH4);
Data.no23=double(mdata.NO23);
Data.tpsi=double(mdata.TPSi);
Data.dsi=double(mdata.DSi);
Data.tpoc=double(mdata.TPOC);
Data.tdoc=double(mdata.TDOC);
Data.o2eq=double(mdata.O2EQ);
Data.doave=double(mdata.DOAVE);
Data.domin=double(mdata.DOMIN);
Data.domax=double(mdata.DOMAX);
Data.ecomsal=double(mdata.ECOMSal);
Data.chlave=double(mdata.Chlave);
Data.chlmin=double(mdata.Chlmin);
Data.chlmax=double(mdata.Chlmax);
Data.gross_pp=double(mdata.Gross_PP);
Data.netpp=double(mdata.NetPP);
Data.tresp=double(mdata.TResp);
Data.ecomtemp=double(mdata.ECOMTemp);
Data.ske=double(mdata.SKE);
return
end